name: Maven CI
on:
  push:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.sourcehawk/**'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - 'OSSMETADATA'
      - '**/README.md'
  pull_request:
    branches:
      - main
      - 'releases/[1-9]+.[0-9]+.x'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.sourcehawk/**'
      - 'attribute.txt'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'INDIVIDUAL_CONTRIBUTOR_LICENSE.md'
      - 'LICENSE'
      - 'NOTICE.txt'
      - 'OSSMETADATA'
      - '**/README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.SONATYPE_GPG_PRIVATE_KEY }}
          gpg-passphrase: SONATYPE_GPG_PASSPHRASE
      - name: Set Maven Project Version
        uses: optum/sourcehawk-parent/github-actions/update-maven-project-version@github-actions
      - name: Build Maven Project
        if: success() && (github.event_name == 'pull_request')
        run: ./mvnw --batch-mode install -D ci.build
      - name: Build Maven Project and Deploy Snapshot
        if: success() && (github.event_name == 'push')
        run: ./mvnw --batch-mode deploy -D ci.deploy
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
